apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: shared
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: gateway-ip-address
  listeners:
    - name: http-root-domain
      hostname: "dawidbladek0831.org"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
    - name: http
      hostname: "*.dawidbladek0831.org"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"

    - name: https-root-domain
      protocol: HTTPS
      port: 443
      hostname: "dawidbladek0831.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: dawidbladek-org-cert-secret
            namespace: shared
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.dawidbladek0831.org"
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway-access: "true"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: dawidbladek-org-cert-secret
            namespace: shared
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dawidbladek0831@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dawidbladek-org-cert
  namespace: shared
spec:
  secretName: dawidbladek-org-cert-secret
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: dawidbladek0831.org
  dnsNames:
    - dawidbladek0831.org
    - temp.dawidbladek0831.org
    - f19.dawidbladek0831.org
    - devf19.dawidbladek0831.org
