apiVersion: v1
kind: Service
metadata:
  name: external-mongo-express
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - name: mongo-express
      port: 8081
      targetPort: 8081