apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: dev
spec:
  serviceName: "headless-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        rel: dev
    spec:
      containers:
        - name: mongo
          image: mongo:8.0-rc
          ports:
            - name: mongo
              containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-config
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
        labels:
          app: mongo
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi