apiVersion: v1
kind: Service
metadata:
  name: synthesizer
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: synthesizer
  ports:
    - name: http
      port: 9023
      targetPort: 80