apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - name: mongo-express
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: headless-mongo
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_INITDB_ROOT_PASSWORD