apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: file-storage-service
  ports:
    - name: http
      port: 9022
      targetPort: 8080