apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:21
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KEYCLOAK_CREATE_ADMIN_USER
              value: "true"
            - name: KEYCLOAK_ADMIN_USER
              value: user
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: password
            - name: KEYCLOAK_DATABASE_HOST
              value: keycloak-postgres-db
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_NAME
              value: postgres
            - name: KEYCLOAK_DATABASE_USER
              value: postgres
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: postgres
            - name: KEYCLOAK_DATABASE_SCHEMA
              value: public
            - name: KEYCLOAK_JDBC_PARAMS
              value: connectTimeout=30000
            - name: KEYCLOAK_ENABLE_HTTPS
              value: "false"