apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
  namespace: f19-dev
spec:
  selector:
    app: file-storage
  type: ClusterIP
  ports:
    - name: HTTP
      port: 80
      targetPort: 8080

---

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: file-storage-service-healthcheck-policy
  namespace: f19-dev
spec:
  default:
    config:
      type: HTTP 
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: /actuator/health
        proxyHeader: NONE
  targetRef:
    group: "" 
    kind: Service
    name: file-storage-service
