apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthesizer
  namespace: f19-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synthesizer
  template:
    metadata:
      labels:
        app: synthesizer
    spec:
      containers:
        - name: synthesizer
          image: ghcr.io/dawidbladek0831/synthesizer:latest
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 50
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 999
---
apiVersion: v1
kind: Service
metadata:
  name: synthesizer-service
  namespace: f19-dev
spec:
  selector:
    app: synthesizer
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: synthesizer-service-backend-policy
  namespace: f19-dev
spec:
  default:
    timeoutSec: 120
  targetRef:
    group: ""
    kind: Service
    name: synthesizer-service
