apiVersion: v1
kind: Service
metadata:
  name: headless-kafka
  namespace: dev
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: internal
      port: 19092
      targetPort: 19092
    - name: controller
      port: 9093
      targetPort: 9093