apiVersion: v1
kind: Service
metadata:
  name: external-kafka-ui
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
    - name: kafka-ui
      port: 9000
      targetPort: 9000