apiVersion: v1
kind: ConfigMap
metadata:
  name: default-page-content
  namespace: shared
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello Ala</title>
    </head>
    <body>
      <h1>Ala ma kota!</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-page-deployment
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-page-deployment
  template:
    metadata:
      labels:
        app: default-page-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: default-page-content
---
apiVersion: v1
kind: Service
metadata:
  name: default-page-service
  namespace: shared
spec:
  selector:
    app: default-page-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
