apiVersion: v1
kind: Service
metadata:
  name: external-mongo
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017