apiVersion: v1
kind: Service
metadata:
  name: headless-mongo
  namespace: dev
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017