apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: dev
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:21
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KEYCLOAK_CREATE_ADMIN_USER
              value: "true"
            - name: KEYCLOAK_ADMIN_USER
              value: user
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: password

            - name: KEYCLOAK_DATABASE_HOST
              value: auth-db-service
            - name: KEYCLOAK_DATABASE_PORT
              value: "5432"
            - name: KEYCLOAK_DATABASE_NAME
              value: postgres
            - name: KEYCLOAK_DATABASE_USER
              value: postgres
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: postgres
            - name: KEYCLOAK_DATABASE_SCHEMA
              value: public
            - name: KEYCLOAK_JDBC_PARAMS
              value: connectTimeout=30000
            - name: KEYCLOAK_ENABLE_HTTPS
              value: "false"
            - name: KEYCLOAK_HOSTNAME
              value: auth.dev.dawidbladek0831.org 
            - name: KEYCLOAK_HOSTNAME_ADMIN
              value: auth.dev.dawidbladek0831.org
            - name: KEYCLOAK_PROXY
              value: edge 
            - name: KEYCLOAK_HTTP_ENABLED
              value: "true"
            - name: KEYCLOAK_ENABLE_HEALTH_ENDPOINTS
              value: "true"
          readinessProbe: 
            httpGet:
              path: /realms/master 
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443