apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: dev
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  gatewayClassName: gke-l7-rilb
  listeners:
    - name: http
      hostname: "*.internal.f19.dev.dawidbladek0831.org"
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.internal.f19.dev.dawidbladek0831.org"
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: internal-f19-dev-dawidbladek-org-cert-secret
            namespace: dev
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
  namespace: dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dawidbladek0831@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-f19-dev-dawidbladek-org-cert
  namespace: dev
spec:
  secretName: internal-f19-dev-dawidbladek-org-cert-secret
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - auth.internal.f19.dev.dawidbladek0831.org
    - synthesizer.internal.f19.dev.dawidbladek0831.org
# ---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: selfsigned-issuer
#   namespace: dev 
# spec:
#   selfSigned: {}
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: dawidbladek0831-org-selfsigned-cert
#   namespace: dev
# spec:
#   secretName: dawidbladek0831-org-selfsigned-cert-secret
#   issuerRef:
#     name: selfsigned-issuer
#     kind: Issuer
#   commonName: internal.f19.dev.dawidbladek0831.org
#   dnsNames:
#     - auth.internal.f19.dev.dawidbladek0831.org
#     - synthesizer.internal.f19.dev.dawidbladek0831.org
#   duration: 2160h # 90 days
#   renewBefore: 360h # 15 days before expiration